# Jekyll configuration

name: axisk.net
description:

# url is currently only used only for the RSS feed in feed.xml
url: 'http://axisk.net'

# baseurl will usually be ''
baseurl: ''

# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: '15794712-3'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
